initially convert original docx to rst
opentelekomcloud-docs/enterprise-dashboard pull request #3
Opened 2021-11-11 10:50 UTC by Nils-Magnus

- converted the original docx document with Pandoc
  - split document into main parts
  - discarded the initial tables and toc that may get autogenerated later on
  - rephrased the main page index.rst
  - linked the main parts from the main page

2023-03-17 12:16 UTC, gtema requested changes

2023-03-17 12:16 UTC, gtema commented on umn/source/appendix.rst
Owner should decide whether this file is necessary at all. I would drop it like we did for all other docs

2023-03-17 12:16 UTC, gtema commented on umn/source/database_tables.rst
> +| ove                  | float8               | None                  |
here as well

2023-03-17 12:16 UTC, gtema commented on umn/source/database_tables.rst
> +| ove                  | float8               | Indicates the         |
and here

2023-03-17 12:16 UTC, gtema commented on umn/source/faq.rst
> +   :width: 6.28617in
I suggest to drop sizing to let browser pick the best. This way they would try to use all available width (but not more then the size of the image)

2023-03-17 12:16 UTC, gtema commented on umn/source/introduction.rst
> +| Enterprise Dashboard    | ✓        | ✓         |          |              |
I assume those are unicode checkmarks. This eventually will lead to problems in PDF build. In all other docs we enforce only ASCII charset

2023-03-17 12:16 UTC, gtema commented on umn/source/media/image02.png
This file is not used

2023-03-20 13:59 UTC, smsk298 commented on umn/source/appendix.rst
file represents old change history of word file, can be removed

2023-03-20 14:11 UTC, smsk298 commented on umn/source/introduction.rst
> +| Enterprise Dashboard    | ✓        | ✓         |          |              |
will be addressed in future change

2023-03-20 22:10 UTC, Nils-Magnus commented on umn/source/appendix.rst
I leave the file as it was part of the original source. It's up to the owner to delete it if he wants to.

2023-03-20 22:11 UTC, Nils-Magnus commented on umn/source/database_tables.rst
> +| amou                  | Float8               | This field displays  |
Widened first column.

2023-03-20 22:11 UTC, Nils-Magnus commented on umn/source/database_tables.rst
> +| ove                  | float8               | None                  |
Widened first column.

2023-03-20 22:11 UTC, Nils-Magnus commented on umn/source/database_tables.rst
> +| ove                  | float8               | Indicates the         |
Widened first column.

2023-03-20 22:21 UTC, Nils-Magnus commented on umn/source/faq.rst
> +   :width: 6.28617in
dropped sizing hints; if necessary, I have a backup

2023-03-20 22:22 UTC, Nils-Magnus commented on umn/source/introduction.rst
> +| Enterprise Dashboard    | ✓        | ✓         |          |              |
Unicode should be supported by proper fonts. The issue might be addressed if it is raised.

2023-03-20 22:32 UTC, Nils-Magnus commented on umn/source/introduction.rst
> +**Note:** Enterprise Dashboard is offered via Direct sales
done

2023-03-20 22:32 UTC, Nils-Magnus commented on umn/source/media/image02.png
removed

2023-03-21 05:39 UTC, gtema approved these changes

2023-03-21 08:52 UTC, vladimirhasko requested changes

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/index.rst
> +   :maxdepth: 2
I think maxdepth: 1 should be enough

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/index.rst
> +   faq
faq could be rather directory containing each faq as a separate file

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/index.rst
> +   database_tables
also here, too much content in single rst. I would recommend to split the chapters to separate rst files and make database_tables directory

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/introduction.rst
> +| Product Versions        | API      | Dashboard | Multi    | Organization |
for what good is Organization management column if it's completely empty?

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/howto.rst
> +How to
in this document there's lot of text and screenshots. It looks quite messy. Introducing caption below (or above) each screenshot would help to keep it more structured

2023-03-21 08:52 UTC, vladimirhasko commented on umn/source/howto.rst
> +Alerts
Extremely bad and confusing to have numbering in text and additional (different) numbering hardcoded in screenshots.
Please remove the numbering from screenshots to make it less confusing

2023-03-22 10:25 UTC, Nils-Magnus commented on umn/source/index.rst
> +   faq
I don't like splitting up pages too much, since then it's much harder to search or keep reading. Additionally, in this case the right-hand navbar becomes completely useless.

As long as a page contains several items **of the same kind** like FA questions or database tables, I think it's fine to have them on one page.

2023-03-22 10:26 UTC, Nils-Magnus commented on umn/source/index.rst
> +   database_tables
see above

2023-03-22 10:27 UTC, Nils-Magnus commented on umn/source/introduction.rst
> +| Product Versions        | API      | Dashboard | Multi    | Organization |
You are right, and I have no idea, but would leave this to the doc owners to decide.

2023-03-22 10:30 UTC, Nils-Magnus commented on umn/source/howto.rst
> +Alerts
Needs to be addressed by doc owners.

2023-03-22 10:45 UTC, vladimirhasko approved these changes

2023-03-22 10:50 UTC, merged